"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type User = { id: string; email: string; displayName: string; isActive: boolean };
type Audit = { id: string; action: string; targetType: string; targetId?: string; createdAt: string };

export default function UsersPage() {
  const [users, setUsers] = useState<User[]>([]); const [audit, setAudit] = useState<Audit[]>([]); const [error, setError] = useState(""); const [created, setCreated] = useState(""); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState("");
  const [form, setForm] = useState({ email: "", displayName: "", password: "" });
  async function load() { setLoading(true); const [usersResponse, auditResponse] = await Promise.all([fetch("http://127.0.0.1:8080/api/v1/users", { credentials: "include" }), fetch("http://127.0.0.1:8080/api/v1/audit", { credentials: "include" })]); if (usersResponse.status === 401 || usersResponse.status === 403) { window.location.href = "/login"; return; } if (!usersResponse.ok) throw new Error(); const data = await usersResponse.json(); setUsers(data.items ?? []); if (auditResponse.ok) setAudit((await auditResponse.json()).items ?? []); setLoading(false); }
  // The request synchronizes this screen with the server after mount.
  useEffect(() => { void load().catch(() => setError("Benutzer konnten nicht geladen werden.")); }, []); // eslint-disable-line react-hooks/set-state-in-effect
  async function create(event: FormEvent) { event.preventDefault(); setCreated(""); setError(""); const response = await fetch("http://127.0.0.1:8080/api/v1/users", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) { setError("Benutzer konnte nicht angelegt werden."); return; } setForm({ email: "", displayName: "", password: "" }); setCreated("Benutzer angelegt."); await load(); }
  async function toggle(user: User) { setBusyId(user.id); setError(""); const response = await fetch(`http://127.0.0.1:8080/api/v1/users/${user.id}/status`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !user.isActive }) }); if (!response.ok) setError(response.status === 409 ? "Der letzte Systemadministrator kann nicht deaktiviert werden." : "Status konnte nicht geändert werden."); else await load(); setBusyId(""); }
  return <main className="content usersPage"><header className="topbar"><div><p className="eyebrow">Administration / Identity</p><h1>Benutzer & Zugriff</h1><p className="muted pageLead">Verwalte Identitäten, Zugriffsstatus und sicherheitsrelevante Aktivitäten.</p></div><nav className="pageNav"><Link className="navLink" href="/">Übersicht</Link><button className="quietButton" onClick={() => void load()}>Aktualisieren</button></nav></header>
    <section className="userLayout"><form className="card createForm" onSubmit={create}><p className="eyebrow">Neuer Zugang</p><h2>Benutzer anlegen</h2><p className="muted">Das Startpasswort wird einmalig gesetzt und sicher gehasht.</p><label>Name<input required value={form.displayName} onChange={(e) => setForm({ ...form, displayName: e.target.value })} /></label><label>E-Mail<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Startpasswort<input required minLength={12} type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><button type="submit">Benutzer anlegen</button>{created && <p className="success" role="status">{created}</p>}</form>
    <section className="card tableCard"><div className="sectionHeading"><div><p className="eyebrow">Verzeichnis</p><h2>Alle Benutzer</h2></div><span className="countBadge">{users.length} Konten</span></div>{error && <p className="formError" role="alert">{error}</p>}{loading ? <p className="muted emptyState">Verzeichnis wird geladen …</p> : users.length === 0 ? <p className="muted emptyState">Noch keine Benutzer angelegt.</p> : <div className="table">{users.map((user) => <div className="tableRow" key={user.id}><span><strong>{user.displayName}</strong><small>{user.email}</small></span><span className="rowActions"><span className={user.isActive ? "pill" : "pill inactive"}>{user.isActive ? "Aktiv" : "Deaktiviert"}</span><button className="smallButton" disabled={busyId === user.id} onClick={() => void toggle(user)}>{user.isActive ? "Deaktivieren" : "Aktivieren"}</button></span></div>)}</div>}</section></section>
    <section className="card auditCard"><div className="sectionHeading"><div><p className="eyebrow">Nachvollziehbarkeit</p><h2>Audit-Protokoll</h2></div><span className="countBadge">Letzte {audit.length}</span></div>{audit.length === 0 ? <p className="muted emptyState">Noch keine Aktivitäten protokolliert.</p> : <div className="auditList">{audit.slice(0, 8).map((event) => <div className="auditRow" key={event.id}><span className="auditDot"/><span><strong>{event.action}</strong><small>{event.targetType} · {event.targetId ?? "–"}</small></span><time>{new Date(event.createdAt).toLocaleString("de-DE")}</time></div>)}</div>}</section></main>;
}
