#!/usr/bin/env bash

# Gemeinsame, ausschliesslich lokale Entwicklungswerte. Die generischen
# POSTGRES_* Variablen werden absichtlich gesetzt, damit eine vorhandene .env
# nicht unbemerkt andere Zugangsdaten in das isolierte Dev-Projekt einmischt.

WERK_DEV_SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
WERK_DEV_ROOT="$(cd -- "${WERK_DEV_SCRIPT_DIR}/.." && pwd)"

: "${WERK_DEV_PROJECT:=werk-dev}"
: "${WERK_DEV_POSTGRES_PORT:=55432}"
: "${WERK_DEV_VALKEY_PORT:=56379}"
: "${WERK_DEV_API_ADDRESS:=127.0.0.1:8081}"
: "${WERK_DEV_API_URL:=http://127.0.0.1:8081}"
: "${WERK_DEV_DASHBOARD_ADDRESS:=127.0.0.1:3000}"

: "${WERK_DEV_POSTGRES_PASSWORD:=werk}"
: "${WERK_DEV_MIGRATOR_PASSWORD:=werk-migrator-dev}"
: "${WERK_DEV_WORK_PASSWORD:=werk-work-dev}"
: "${WERK_DEV_IDENTITY_PASSWORD:=werk-identity-dev}"
: "${WERK_DEV_ADMIN_PASSWORD:=werk-admin-dev}"
: "${WERK_DEV_SERVICE_PASSWORD:=werk-service-dev}"
: "${WERK_DEV_WORKER_PASSWORD:=werk-worker-dev}"
: "${WERK_DEV_BACKUP_PASSWORD:=werk-backup-dev}"

: "${WERK_DEV_MIGRATOR_DATABASE_URL:=postgres://werk_migrator:${WERK_DEV_MIGRATOR_PASSWORD}@127.0.0.1:${WERK_DEV_POSTGRES_PORT}/werk?sslmode=disable}"
: "${WERK_DEV_WORK_DATABASE_URL:=postgres://werk_work_runtime:${WERK_DEV_WORK_PASSWORD}@127.0.0.1:${WERK_DEV_POSTGRES_PORT}/werk?sslmode=disable}"
: "${WERK_DEV_IDENTITY_DATABASE_URL:=postgres://werk_identity_runtime:${WERK_DEV_IDENTITY_PASSWORD}@127.0.0.1:${WERK_DEV_POSTGRES_PORT}/werk?sslmode=disable}"
: "${WERK_DEV_WORKER_DATABASE_URL:=postgres://werk_worker_runtime:${WERK_DEV_WORKER_PASSWORD}@127.0.0.1:${WERK_DEV_POSTGRES_PORT}/werk?sslmode=disable}"
: "${WERK_DEV_VALKEY_URL:=redis://127.0.0.1:${WERK_DEV_VALKEY_PORT}}"

WERK_ENV=development
: "${WERK_BUILD_VERSION:=dev-local}"
WERK_DEV_BUILD_DIR="${WERK_DEV_ROOT}/.dev/bin"

POSTGRES_PASSWORD="${WERK_DEV_POSTGRES_PASSWORD}"
POSTGRES_MIGRATOR_PASSWORD="${WERK_DEV_MIGRATOR_PASSWORD}"
POSTGRES_WORK_PASSWORD="${WERK_DEV_WORK_PASSWORD}"
POSTGRES_IDENTITY_PASSWORD="${WERK_DEV_IDENTITY_PASSWORD}"
POSTGRES_ADMIN_PASSWORD="${WERK_DEV_ADMIN_PASSWORD}"
POSTGRES_SERVICE_PASSWORD="${WERK_DEV_SERVICE_PASSWORD}"
POSTGRES_WORKER_PASSWORD="${WERK_DEV_WORKER_PASSWORD}"
POSTGRES_BACKUP_PASSWORD="${WERK_DEV_BACKUP_PASSWORD}"

export WERK_DEV_ROOT WERK_DEV_PROJECT
export WERK_DEV_POSTGRES_PORT WERK_DEV_VALKEY_PORT
export WERK_DEV_API_ADDRESS WERK_DEV_API_URL WERK_DEV_DASHBOARD_ADDRESS
export WERK_DEV_MIGRATOR_DATABASE_URL WERK_DEV_WORK_DATABASE_URL
export WERK_DEV_IDENTITY_DATABASE_URL
export WERK_DEV_WORKER_DATABASE_URL WERK_DEV_VALKEY_URL WERK_DEV_BUILD_DIR
export WERK_ENV WERK_BUILD_VERSION
export POSTGRES_PASSWORD POSTGRES_MIGRATOR_PASSWORD POSTGRES_WORK_PASSWORD
export POSTGRES_IDENTITY_PASSWORD
export POSTGRES_ADMIN_PASSWORD POSTGRES_SERVICE_PASSWORD POSTGRES_WORKER_PASSWORD
export POSTGRES_BACKUP_PASSWORD
